### PR TITLE
Made code work with ESP-IDF v5.2.3.

### PR DESCRIPTION
**Pull request by jthiem**
Code compiles and runs with ESP-IDF 5.2.3 in Linux. Tested with an Apple keyboard.

### CODE REVIEW

**Comment by RBDSeb** [comment]
ahah nice! I was busy on the same thing this morning... (with esp-idf 5.3.1) and obviously had to make the same changes. However, when testing it, I get a reboot of the esp32 as soon as I get a key event... 
`rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)`
have you seen something similar (didn't search of it yet)?

tested with keychron k3 keyboard and esp32Wroom...

thanks :)

**Comment by jthiem** [comment]
Huh, I get reboots of the ESP32 on _certain_ keys, especially the "fn" key. An event buffer or a callback buffer not big enough?

**Comment by jthiem** [comment]
> ahah nice! I was busy on the same thing this morning... (with esp-idf 5.3.1) and obviously had to make the same changes. However, when testing it, I get a reboot of the esp32 as soon as I get a key event... `rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)` have you seen something similar (didn't search of it yet)?
> 
> tested with keychron k3 keyboard and esp32Wroom...
> 
> thanks :)

I may have found the reason, please see issue #9.

Cheers!

**Comment by jthiem** [comment]
Added bugfix for #9, with some simplification to develop a decoding state machine. Need to adapt BTKeyboard::wait_for_ascii_char for the new code.

**Comment by RBDSeb** [comment]
Nice catch! works well for me on ESP-IDF v5.3.1.

**Comment by turgu1** [comment]
Thanks a lot for your contribution!

**Pull request merged**
